# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\PythonProject\K224161806\salemanagement\ui\loginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1171, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, -20, 641, 171))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 130, 401, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineeidtusername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineeidtusername.setGeometry(QtCore.QRect(390, 150, 461, 41))
        self.lineeidtusername.setObjectName("lineeidtusername")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 220, 361, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditpassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditpassword.setGeometry(QtCore.QRect(390, 240, 471, 51))
        self.lineEditpassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditpassword.setObjectName("lineEditpassword")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 162, 131, 261))
        self.label_5.setLineWidth(12)
        self.label_5.setMidLineWidth(12)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(
            "/SalesManagement/Images/131507_hacker_administrator_system_sys_hack_icon.png"))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 460, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/SalesManagement/Images/131507_hacker_administrator_system_sys_hack_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 460, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/SalesManagement/Images/131507_hacker_administrator_system_sys_hack_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(260, 350, 471, 17))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1171, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Đăng nhập hệ thống"))
        self.label_2.setText(_translate("MainWindow", "User name : "))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.pushButton.setText(_translate("MainWindow", "Đăng nhập"))
        self.pushButton_2.setText(_translate("MainWindow", "Thoát"))
        self.checkBox.setText(_translate("MainWindow", "Lưu thông tin đăng nhập"))
