# Form implementation generated from reading ui file '/Users/minhtan/Documents/GitHub/ML-in-BA/K22416C/SalesManagement/UI/MainProgramMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 10, 471, 81))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuH_th_ng = QtWidgets.QMenu(parent=self.menubar)
        self.menuH_th_ng.setObjectName("menuH_th_ng")
        self.menuQuanly = QtWidgets.QMenu(parent=self.menubar)
        self.menuQuanly.setObjectName("menuQuanly")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionthongtintaikhoan = QtGui.QAction(parent=MainWindow)
        self.actionthongtintaikhoan.setShortcut("")
        self.actionthongtintaikhoan.setObjectName("actionthongtintaikhoan")
        self.actiondoimatkhau = QtGui.QAction(parent=MainWindow)
        self.actiondoimatkhau.setObjectName("actiondoimatkhau")
        self.actioncauhinhhethong = QtGui.QAction(parent=MainWindow)
        self.actioncauhinhhethong.setObjectName("actioncauhinhhethong")
        self.actionthoatphanmem = QtGui.QAction(parent=MainWindow)
        self.actionthoatphanmem.setObjectName("actionthoatphanmem")
        self.actionQuanlydanhmucsanpham = QtGui.QAction(parent=MainWindow)
        self.actionQuanlydanhmucsanpham.setCheckable(False)
        self.actionQuanlydanhmucsanpham.setChecked(False)
        self.actionQuanlydanhmucsanpham.setObjectName("actionQuanlydanhmucsanpham")
        self.actionQuanlydonhang = QtGui.QAction(parent=MainWindow)
        self.actionQuanlydonhang.setObjectName("actionQuanlydonhang")
        self.actionQuanlynhanvien = QtGui.QAction(parent=MainWindow)
        self.actionQuanlynhanvien.setObjectName("actionQuanlynhanvien")
        self.menuH_th_ng.addAction(self.actionthongtintaikhoan)
        self.menuH_th_ng.addAction(self.actiondoimatkhau)
        self.menuH_th_ng.addAction(self.actioncauhinhhethong)
        self.menuH_th_ng.addAction(self.actionthoatphanmem)
        self.menuH_th_ng.addSeparator()
        self.menuQuanly.addAction(self.actionQuanlydanhmucsanpham)
        self.menuQuanly.addAction(self.actionQuanlydonhang)
        self.menuQuanly.addAction(self.actionQuanlynhanvien)
        self.menubar.addAction(self.menuH_th_ng.menuAction())
        self.menubar.addAction(self.menuQuanly.menuAction())

        self.retranslateUi(MainWindow)
        self.actionthoatphanmem.changed.connect(MainWindow.close) # type: ignore
        self.actionQuanlydanhmucsanpham.changed.connect(MainWindow.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Đây là màn hình chính"))
        self.menuH_th_ng.setTitle(_translate("MainWindow", "Hệ thống"))
        self.menuQuanly.setTitle(_translate("MainWindow", "Quản lý"))
        self.actionthongtintaikhoan.setText(_translate("MainWindow", "Thông tin tài khoản"))
        self.actiondoimatkhau.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.actioncauhinhhethong.setText(_translate("MainWindow", "Cấu hình hệ thống"))
        self.actionthoatphanmem.setText(_translate("MainWindow", "Thoát phần mềm"))
        self.actionthoatphanmem.setShortcut(_translate("MainWindow", "Esc"))
        self.actionQuanlydanhmucsanpham.setText(_translate("MainWindow", "Quản lý danh mục sản phẩm"))
        self.actionQuanlydonhang.setText(_translate("MainWindow", "Quản lý đơn hàng"))
        self.actionQuanlynhanvien.setText(_translate("MainWindow", "Quản lý nhân viên"))
